#!/bin/bash

set -e

NC="\e[0m"
SUCCESS="\e[42m"
WARNING="\e[43m"
ERROR="\e[41m"

trap 'echo -e "${ERROR}Deployment failed${NC}"' ERR

CONTAINER_NAME="php_jeroendn"
GIT_BRANCH="master"
GIT_REMOTE="origin"

if [ "$EUID" -eq 0 ]; then
  echo -e "${ERROR}Do not run as sudo!${NC}"
  exit 1
fi

echo -e "${SUCCESS}Please enter your sudo password:${NC}"
sudo -v

echo -e "${SUCCESS}Pulling latest changes${NC}"
git reset --hard
git checkout $GIT_BRANCH
git fetch $GIT_REMOTE
git pull $GIT_REMOTE $GIT_BRANCH

echo -e "${SUCCESS}Rebuilding Docker image${NC}"
sudo docker compose build

echo -e "${SUCCESS}Restarting Docker containers${NC}"
sudo docker compose down
sudo docker compose up -d

echo -e "${SUCCESS}Installing libraries${NC}"
sudo docker exec -it $CONTAINER_NAME composer install
sudo docker exec -it $CONTAINER_NAME npm install
sudo docker exec -it $CONTAINER_NAME npx modclean -r -n default:safe,default:caution

echo -e "${SUCCESS}Running migrations${NC}"
sudo docker exec -it $CONTAINER_NAME php artisan migrate --force

echo -e "${SUCCESS}Building assets${NC}"
sudo docker exec -it $CONTAINER_NAME npm run build

echo -e "${SUCCESS}Deployment finished${NC}"
