#!/bin/bash

NC='\033[0m'
SUCCESS='\e[32m'

GIT_BRANCH="master"
GIT_REMOTE="origin"

echo "${SUCCESS}Pulling latest changes${NC}"
git checkout $GIT_BRANCH
git fetch $GIT_REMOTE
git pull $GIT_REMOTE $GIT_BRANCH

echo "${SUCCESS}Restarting Docker containers${NC}"
docker-compose down
docker-compose up -d --build

echo "${SUCCESS}Installing libraries${NC}"
docker exec -it php_jeroendn ./develop install

echo "${SUCCESS}Deployment complete${NC}"
