version: '3.8'

services:
  php_jeroendn:
    hostname: jeroendn
    build: docker/php/.
    image: php_jeroendn:apache
    container_name: php_jeroendn
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - caddy_net
    ports:
      - "${HTTP_PORT}:9000"

networks:
  caddy_net:
    external: true
