services:
  php:
    hostname: jeroendn
    build: docker/php/.
    image: php_jeroendn:apache
    container_name: php_jeroendn
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - ./:/var/www/html
    networks:
      - docker_server_caddy
      - docker_server_database

networks:
  docker_server_caddy:
    external: true
  docker_server_database:
    external: true
